### ISSUE TITLE
XCDYouTubeKit 2.0.3 doc was not built

### ISSUE THREAD

**Issue by 0xced** [CocoaPods/cocoadocs.org#265]
I have released [XCDYouTubeKit 2.0.3](https://github.com/CocoaPods/Specs/blob/master/Specs/XCDYouTubeKit/2.0.3/XCDYouTubeKit.podspec.json) 12 days ago and its [documentation](http://cocoadocs.org/docsets/XCDYouTubeKit/2.0.3/) was not built.

Is it a know issue or was I just unlucky?

**Comment by 0xced** [comment]
Any news about this issue?

**Comment by orta** [comment]
Hrm. It's crashing Appledoc.

```sh
~/s/h/S/cocoadocs.org  $
appledoc --project-name XCDYouTubeKit --project-company "Cédric Luthi" --index-desc resources/overwritten_index.html --company-id com.cocoadocs.xcdyoutubekit --project-version 2.0.3 --no-install-docset --templates "/Users/orta/spiel/html/Strata/cocoadocs.org/activity/template/XCDYouTubeKit/" --verbose 5 --keep-intermediate-files --create-html --publish-docset --docset-feed-url http://cocoadocs.org/docsets/XCDYouTubeKit/xcode-docset.atom --docset-atom-filename xcode-docset.atom --docset-package-url http://cocoadocs.org/docsets/XCDYouTubeKit/docset.xar --docset-package-filename docset --docset-fallback-url http://cocoadocs.org/docsets/XCDYouTubeKit --docset-feed-name XCDYouTubeKit --keep-undocumented-objects --keep-undocumented-members --search-undocumented-doc  --output "/Users/orta/spiel/html/Strata/cocoadocs.org/activity/docsets/XCDYouTubeKit/2.0.3/" /Users/orta/spiel/html/Strata/cocoadocs.org/activity/download/XCDYouTubeKit/2.0.3/XCDYouTubeKit/XCDYouTubeKit/XCDYouTubeClient.h /Users/orta/spiel/html/Strata/cocoadocs.org/activity/download/XCDYouTubeKit/2.0.3/XCDYouTubeKit/XCDYouTubeKit/XCDYouTubeError.h /Users/orta/spiel/html/Strata/cocoadocs.org/activity/download/XCDYouTubeKit/2.0.3/XCDYouTubeKit/XCDYouTubeKit/XCDYouTubeKit.h /Users/orta/spiel/html/Strata/cocoadocs.org/activity/download/XCDYouTubeKit/2.0.3/XCDYouTubeKit/XCDYouTubeKit/XCDYouTubeOperation.h /Users/orta/spiel/html/Strata/cocoadocs.org/activity/download/XCDYouTubeKit/2.0.3/XCDYouTubeKit/XCDYouTubeKit/XCDYouTubeVideo.h /Users/orta/spiel/html/Strata/cocoadocs.org/activity/download/XCDYouTubeKit/2.0.3/XCDYouTubeKit/XCDYouTubeKit/XCDYouTubeVideoOperation.h /Users/orta/spiel/html/Strata/cocoadocs.org/activity/download/XCDYouTubeKit/2.0.3/XCDYouTubeKit/XCDYouTubeKit/XCDYouTubeVideoPlayerViewController.h
appledoc version: 2.2 (build 963)



NORMAL | Initializing...
NORMAL | Parsing source files...
VERBOSE | Parsing objects from 7 paths...
INFO | Parsing source code from '/Users/orta/spiel/html/Strata/cocoadocs.org/activity/download/XCDYouTubeKit/2.0.3/XCDYouTubeKit/XCDYouTubeKit/XCDYouTubeClient.h'...
INFO | Parsing source code from '/Users/orta/spiel/html/Strata/cocoadocs.org/activity/download/XCDYouTubeKit/2.0.3/XCDYouTubeKit/XCDYouTubeKit/XCDYouTubeError.h'...
VERBOSE | Matched XCDYouTubeErrorCode typedef enum definition at line 15.
INFO | Parsing source code from '/Users/orta/spiel/html/Strata/cocoadocs.org/activity/download/XCDYouTubeKit/2.0.3/XCDYouTubeKit/XCDYouTubeKit/XCDYouTubeKit.h'...
INFO | Parsing source code from '/Users/orta/spiel/html/Strata/cocoadocs.org/activity/download/XCDYouTubeKit/2.0.3/XCDYouTubeKit/XCDYouTubeKit/XCDYouTubeOperation.h'...
VERBOSE | Matched XCDYouTubeOperation protocol definition at line 0.
INFO | Parsing source code from '/Users/orta/spiel/html/Strata/cocoadocs.org/activity/download/XCDYouTubeKit/2.0.3/XCDYouTubeKit/XCDYouTubeKit/XCDYouTubeVideo.h'...
VERBOSE | Matched XCDYouTubeVideoQuality typedef enum definition at line 12.
fish: Job 1, 'appledoc --project-name XCDYouTubeKit --project-company "Cédric Luthi" --index-desc resources/overwritten_index.html --company-id com.cocoadocs.xcdyoutubekit --project-version 2.0.3 --no-install-docset --templates "/Users/orta/spiel/html/Strata/cocoadocs.org/activity/template/XCDYouTubeKit/" --verbose 5 --keep-intermediate-files --create-html --publish-docset --docset-feed-url http://cocoadocs.org/docsets/XCDYouTubeKit/xcode-docset.atom --docset-atom-filename xcode-docset.atom --docset-package-url http://cocoadocs.org/docsets/XCDYouTubeKit/docset.xar --docset-package-filename docset --docset-fallback-url http://cocoadocs.org/docsets/XCDYouTubeKit --docset-feed-name XCDYouTubeKit --keep-undocumented-objects --keep-undocumented-members --search-undocumented-doc  --output "/Users/orta/spiel/html/Strata/cocoadocs.org/activity/docsets/XCDYouTubeKit/2.0.3/" /Users/orta/spiel/html/Strata/cocoadocs.org/activity/download/XCDYouTubeKit/2.0.3/XCDYouTubeKit/XCDYouTubeKit/XCDYouTubeClient.h /Users/orta/spiel/html/Strata/cocoadocs.org/activity/download/XCDYouTubeKit/2.0.3/XCDYouTubeKit/XCDYouTubeKit/XCDYouTubeError.h /Users/orta/spiel/html/Strata/cocoadocs.org/activity/download/XCDYouTubeKit/2.0.3/XCDYouTubeKit/XCDYouTubeKit/XCDYouTubeKit.h /Users/orta/spiel/html/Strata/cocoadocs.org/activity/download/XCDYouTubeKit/2.0.3/XCDYouTubeKit/XCDYouTubeKit/XCDYouTubeOperation.h /Users/orta/spiel/html/Strata/cocoadocs.org/activity/download/XCDYouTubeKit/2.0.3/XCDYouTubeKit/XCDYouTubeKit/XCDYouTubeVideo.h /Users/orta/spiel/html/Strata/cocoadocs.org/activity/download/XCDYouTubeKit/2.0.3/XCDYouTubeKit/XCDYouTubeKit/XCDYouTubeVideoOperation.h /Users/orta/spiel/html/Strata/cocoadocs.org/activity/download/XCDYouTubeKit/2.0.3/XCDYouTubeKit/XCDYouTubeKit/XCDYouTubeVideoPlayerViewController.h' terminated by signal SIGSEGV (Address boundary error)
```

**Comment by orta** [comment]
Removing `/Users/orta/spiel/html/Strata/cocoadocs.org/activity/download/XCDYouTubeKit/2.0.3/XCDYouTubeKit/XCDYouTubeKit/XCDYouTubeVideo.h` from the  list of files to be doc'd doesn't crash it.

**Comment by 0xced** [comment]
It looks like you are not using appledoc from HEAD anymore. As discussed in #160, appledoc 2.2 (build 963) crashes on XCDYouTubeVideo.h because of the [DEPRECATED_MSG_ATTRIBUTE](https://github.com/0xced/XCDYouTubeKit/blob/2.0.3/XCDYouTubeKit/XCDYouTubeVideo.h#L37) macro in the enum.

**Comment by orta** [comment]
cool cool, will take a look at updating brew when the VPS is alive again.

**Comment by orta** [comment]
@segiddins just updated it to the latest master

**Comment by 0xced** [comment]
I clicked the re-parse button but the 2.0.3 docset is still not available. Also, the *Potential error info* button points to http://199.229.252.196:4567/error/XCDYouTubeKit/2.0.3 which does not respond.

**Comment by segiddins** [comment]
As status.cocoapods.org says, the CocoaDocs server is down for maintenance. 

-Samuel E. Giddins

On Jan 12, 2015, at 12:39 PM, Cédric Luthi <notifications@github.com> wrote:

I clicked the re-parse button but the 2.0.3 docset is still not available. Also, the Potential error info button points to http://199.229.252.196:4567/error/XCDYouTubeKit/2.0.3 which does not respond.

**Comment by 0xced** [comment]
Incredible coincidence: [appledoc 2.2.1 build 1333](https://github.com/tomaz/appledoc/releases) was released 3 hours ago. The binary release is not yet available though.

**Comment by 0xced** [comment]
Ha! I should have checked status.cocoapods.org, thanks for the update @segiddins.

**Comment by segiddins** [comment]
@0xced the server is now back up, and I've manually triggered a re-parse.

**Comment by 0xced** [comment]
Maybe I’m too impatient or a database issue occurred after the maintenance. Here is the error I get:
> unable to open database file
```
/Users/orta/cocoadocs/vendor/bundle/ruby/2.1.0/gems/docstat-1.0.4/lib/docstat/container.rb:25:in `initialize'
/Users/orta/cocoadocs/vendor/bundle/ruby/2.1.0/gems/docstat-1.0.4/lib/docstat/container.rb:25:in `new'
/Users/orta/cocoadocs/vendor/bundle/ruby/2.1.0/gems/docstat-1.0.4/lib/docstat/container.rb:25:in `from_sqlite'
/Users/orta/cocoadocs/vendor/bundle/ruby/2.1.0/gems/docstat-1.0.4/lib/docstat.rb:48:in `containers_from_docset'
/Users/orta/cocoadocs/vendor/bundle/ruby/2.1.0/gems/docstat-1.0.4/lib/docstat.rb:33:in `process'
/Users/orta/cocoadocs/classes/docset_fixer.rb:65:in `get_doc_percent'
/Users/orta/cocoadocs/classes/docset_fixer.rb:34:in `post_process'
/Users/orta/cocoadocs/classes/docset_fixer.rb:19:in `fix'
/Users/orta/cocoadocs/./cocoadocs.rb:426:in `document_spec'
/Users/orta/cocoadocs/./cocoadocs.rb:490:in `document_spec_at_path'
/Users/orta/cocoadocs/./cocoadocs.rb:142:in `block in doc'
/Users/orta/cocoadocs/./cocoadocs.rb:137:in `each'
/Users/orta/cocoadocs/./cocoadocs.rb:137:in `doc'
/Users/orta/cocoadocs/./cocoadocs.rb:209:in `block in cocoadocs_url'
/Users/orta/.rbenv/versions/2.1.3/lib/ruby/2.1.0/open-uri.rb:153:in `open_uri'
/Users/orta/.rbenv/versions/2.1.3/lib/ruby/2.1.0/open-uri.rb:704:in `open'
/Users/orta/.rbenv/versions/2.1.3/lib/ruby/2.1.0/open-uri.rb:34:in `open'
/Users/orta/cocoadocs/./cocoadocs.rb:206:in `cocoadocs_url'
/Users/orta/cocoadocs/./cocoadocs.rb:158:in `cocoadocs'
/Users/orta/cocoadocs/./cocoadocs.rb:114:in `initialize'
/Users/orta/cocoadocs/./cocoadocs.rb:509:in `new'
/Users/orta/cocoadocs/./cocoadocs.rb:509:in `<main>'
```

**Comment by segiddins** [comment]
That means the `docstat` gem we use is unable to open the index file inside the docset.

**Comment by 0xced** [comment]
The *Potential error info* button does not display information anymore but the docset is still not available. Is there something I can do to help resolving this issue?

**Comment by orta** [comment]
Well, you could remove that line in comments that crashes `appledoc`, we may have to revert to an older `appledoc` build as it is introducing instability in other [pods](https://github.com/CocoaPods/cocoadocs.org/issues/284). Looking ATM.

**Comment by orta** [comment]
I've got CocoaDocs vending it's own appledoc version now, specifically the released version from 8 days ago, and your Pod is docing fine :+1: 

http://cocoadocs.org/docsets/XCDYouTubeKit/2.0.3/

**Comment by 0xced** [comment]
Excellent, thank you!

**Comment by orta** [comment]
or not :/ 

all the files are completely empty.

**Comment by orta** [comment]
https://github.com/tomaz/appledoc/pull/501

**Comment by orta** [comment]
I manually changed all our templates to the new syntax. Works fine.

**Comment by 0xced** [comment]
You rock! 🎸
