### ISSUE TITLE
Unable to preview pods that use a http source

### ISSUE THREAD

**Issue by abarisain** [CocoaPods/cocoadocs.org#315]
Hi ! 
I was trying to investigate why a Pod 404s on cocoadocs, so I tried the CLI cocoadocs preview command.

It seems to fail on pods with a "http" source, as opposed to a "git" one, like sqlite3.
Running `bundle exec ./cocoadocs.rb preview sqlite3 --verbose` gives me the following error :

```
  Looking at sqlite3 master 

--------------/Users/arnaud/dev/cocoadocs.org/activity/cocoadocs_specs/Specs/sqlite3/3.8.8.3/sqlite3.podspec.json-------------
Unrecognized options `[:tag]`
------
["/usr/local/lib/ruby/gems/2.1.0/gems/cocoapods-downloader-0.8.1/lib/cocoapods-downloader/base.rb:54:in `initialize'", "/usr/local/lib/ruby/gems/2.1.0/gems/cocoapods-downloader-0.8.1/lib/cocoapods-downloader.rb:70:in `new'", "/usr/local/lib/ruby/gems/2.1.0/gems/cocoapods-downloader-0.8.1/lib/cocoapods-downloader.rb:70:in `for_target'", "/Users/arnaud/dev/cocoadocs.org/classes/source_downloader.rb:33:in `block in download_pod_source_files'", "/usr/local/Cellar/ruby/2.1.4/lib/ruby/2.1.0/timeout.rb:91:in `block in timeout'", "/usr/local/Cellar/ruby/2.1.4/lib/ruby/2.1.0/timeout.rb:35:in `block in catch'", "/usr/local/Cellar/ruby/2.1.4/lib/ruby/2.1.0/timeout.rb:35:in `catch'", "/usr/local/Cellar/ruby/2.1.4/lib/ruby/2.1.0/timeout.rb:35:in `catch'", "/usr/local/Cellar/ruby/2.1.4/lib/ruby/2.1.0/timeout.rb:106:in `timeout'", "/Users/arnaud/dev/cocoadocs.org/classes/source_downloader.rb:32:in `download_pod_source_files'", "./cocoadocs.rb:392:in `document_spec'", "./cocoadocs.rb:511:in `document_spec_at_path'", "./cocoadocs.rb:259:in `preview'", "./cocoadocs.rb:114:in `initialize'", "./cocoadocs.rb:530:in `new'", "./cocoadocs.rb:530:in `<main>'"]
* - http://cocoadocs.org/docsets/sqlite3/3.8.8.3/
 open "/Users/arnaud/dev/cocoadocs.org/activity/docsets/sqlite3/3.8.8.3/"
The file /Users/arnaud/dev/cocoadocs.org/activity/docsets/sqlite3/3.8.8.3 does not exist.
open "/Users/arnaud/dev/cocoadocs.org/activity/docsets/sqlite3/3.8.8.3/" failed!
Preview: "/Users/arnaud/dev/cocoadocs.org/activity/docsets/sqlite3/3.8.8.3/"
```

Adding a "tag" attribute to the source (and passing --skip-fetch-specs) doesn't work.

**Comment by segiddins** [comment]
That should only be an issue with the `preview` command

**Comment by abarisain** [comment]
Yep, sorry about the 404 mention, it only brings confusion.

**Comment by orta** [comment]
interesting, would definitely accept a PR fixing this :+1:

**Comment by abarisain** [comment]
I have never done any Ruby, but I'll give it a shot! According to the logs, I wonder if this does not belong in the cocoapods-downloader project, but the other commands work, so I don't know yet.

**Comment by abarisain** [comment]
Thanks !

**Comment by orta** [comment]
no worries
