### ISSUE TITLE
Testing idealist can crash when opening project's xcodeproj

### ISSUE THREAD

**Issue by orta** [CocoaPods/cocoadocs.org#345]
```
/Users/maddern/.rvm/gems/ruby-2.1.3/gems/xcodeproj-0.23.1/lib/xcodeproj/project.rb:206:in `initialize_from_file'
/Users/maddern/.rvm/gems/ruby-2.1.3/gems/xcodeproj-0.23.1/lib/xcodeproj/project.rb:91:in `open'
/Users/maddern/dev/cocoadocs.org/classes/testing_idealist.rb:90:in `path_to_project'
```

**Comment by orta** [comment]
Could be 6.3 support? https://github.com/paweldudek/PBDNotificationObserver/blob/master/PBDNotificationObserver.xcodeproj/project.pbxproj#L231

**Comment by orta** [comment]
I wrapped this with an exception catcher, in https://github.com/CocoaPods/cocoadocs.org/commit/f21fdeac68448c33c3c40658283fb6f535b6b295 as there was a library whose xcodeproject would crash xcodeproj.
