### ISSUE TITLE
Deal with nil podspecs?

### ISSUE THREAD

**Issue by orta** [CocoaPods/cocoadocs.org#350]
```
--------------/Users/jane/dev/cocoadocs.org/activity/cocoadocs_specs/Specs/CLPlacemark-StateAbbreviation/0.1.0/CLPlacemark-StateAbbreviation.podspec.json-------------
undefined method `name' for nil:NilClass
------
["/Users/jane/dev/cocoadocs.org/classes/readme_manipulator.rb:81:in `remove_named_header'", "/Users/jane/dev/cocoadocs.org/classes/readme_manipulator.rb:13:in `run_for_cocoadocs'", "/Users/jane/dev/cocoadocs.org/classes/docset_fixer.rb:17:in `fix'", "cocoadocs.rb:448:in `document_spec'", "cocoadocs.rb:519:in `document_spec_with_name'", "cocoadocs.rb:157:in `block in doc'", "cocoadocs.rb:150:in `each'", "cocoadocs.rb:150:in `doc'", "cocoadocs.rb:206:in `cocoadocs_doc'", "cocoadocs.rb:166:in `cocoadocs'", "cocoadocs.rb:114:in `initialize'", "cocoadocs.rb:531:in `new'", "cocoadocs.rb:531:in `<main>'"]
* - http://cocoadocs.org/docsets/CLPlacemark-StateAbbreviation/0.1.0/

```

**Comment by orta** [comment]
Closing, whatever this was - it's probably done now.
