### ISSUE TITLE
Doc not generated for FolioReaderKit

### ISSUE THREAD

**Issue by hebertialmeida** [CocoaPods/cocoadocs.org#424]
I have created https://github.com/FolioReader/FolioReaderKit and now I am improving the documentation. I have generated it locally using Jazzy, it worked perfectly.

All seems good, but yet it doesn't show up correctly on the cocoadocs.org.

I have cloned cocoadocs.org locally to preview the generation but I got an error `No podspec exists at path FolioReaderKit.podspec.`

This is the console log:

```
Hebertis-MacBook-Air:cocoadocs.org hebertialmeida$ bundle exec ./cocoadocs.rb preview FolioReaderKit
From git://github.com/CocoaPods/Specs
 * branch            master     -> FETCH_HEAD

 Looking at FolioReaderKit master 

 > Git download
Using config file /Users/hebertialmeida/Projetos/2016/cocoadocs.org/activity/download/FolioReaderKit/0.5.0/FolioReaderKit/.jazzy.yaml
--------------/Users/hebertialmeida/Projetos/2016/cocoadocs.org/activity/cocoadocs_specs/Specs/FolioReaderKit/0.5.0/FolioReaderKit.podspec.json-------------
[!] No podspec exists at path `FolioReaderKit.podspec`.
------
["/Users/hebertialmeida/.rvm/gems/ruby-2.1.3/gems/cocoapods-core-0.39.0/lib/cocoapods-core/specification.rb:530:in `from_file'", "/Users/hebertialmeida/.rvm/gems/ruby-2.1.3/gems/jazzy-0.5.0/lib/jazzy/podspec_documenter.rb:30:in `create_podspec'", "/Users/hebertialmeida/.rvm/gems/ruby-2.1.3/gems/jazzy-0.5.0/lib/jazzy/config.rb:185:in `block in <class:Config>'", "/Users/hebertialmeida/.rvm/gems/ruby-2.1.3/gems/jazzy-0.5.0/lib/jazzy/config.rb:34:in `instance_exec'", "/Users/hebertialmeida/.rvm/gems/ruby-2.1.3/gems/jazzy-0.5.0/lib/jazzy/config.rb:34:in `set'", "/Users/hebertialmeida/.rvm/gems/ruby-2.1.3/gems/jazzy-0.5.0/lib/jazzy/config.rb:43:in `set_if_unconfigured'", "/Users/hebertialmeida/.rvm/gems/ruby-2.1.3/gems/jazzy-0.5.0/lib/jazzy/config.rb:352:in `block in parse_config_file'", "/Users/hebertialmeida/.rvm/gems/ruby-2.1.3/gems/jazzy-0.5.0/lib/jazzy/config.rb:349:in `each'", "/Users/hebertialmeida/.rvm/gems/ruby-2.1.3/gems/jazzy-0.5.0/lib/jazzy/config.rb:349:in `parse_config_file'", "./cocoadocs.rb:431:in `block in document_spec'", "./cocoadocs.rb:429:in `tap'", "./cocoadocs.rb:429:in `document_spec'", "./cocoadocs.rb:535:in `document_spec_at_path'", "./cocoadocs.rb:270:in `preview'", "./cocoadocs.rb:115:in `initialize'", "./cocoadocs.rb:567:in `new'", "./cocoadocs.rb:567:in `<main>'"]
* - http://cocoadocs.org/docsets/FolioReaderKit/0.5.0/
The file /Users/hebertialmeida/Projetos/2016/cocoadocs.org/activity/docsets/FolioReaderKit/0.5.0 does not exist.
open "/Users/hebertialmeida/Projetos/2016/cocoadocs.org/activity/docsets/FolioReaderKit/0.5.0/" failed!
Preview: "/Users/hebertialmeida/Projetos/2016/cocoadocs.org/activity/docsets/FolioReaderKit/0.5.0/"
```

I have a `FolioReaderKit.podspec` and also a `.jazzy.yaml` on the project root.

**Comment by orta** [comment]
Hrm, it's likely that the `podspec: FolioReaderKit.podspec` is overwriting the one provided for CocoaDocs

**Comment by hebertialmeida** [comment]
Same error on API, http://api.cocoadocs.org:4567/error/FolioReaderKit/0.5.0

@orta is there anything that I can do?

**Comment by orta** [comment]
I think CocoaDocs need to sanitise the yaml file to remove the `podspec` attribute in this case

**Comment by hebertialmeida** [comment]
I don't know for CocoaDocs but locally Jazzy needs `podspec` to generate the docs

**Comment by orta** [comment]
I've just checked this after #508 and it looks 👍 

http://cocoadocs.org/docsets/FolioReaderKit/1.1.0/
