### ISSUE TITLE
Docs not generated after adding .cocoadocs.yaml

### ISSUE THREAD

**Issue by Damol** [CocoaPods/cocoadocs.org#436]
With the latest beta release of our Pod we wanted to add styling to our CocoaDocs page, so we put the `.cocoadocs.yaml` file in the root of our repository: https://github.com/goprimer/primer-ios-sdk.

But this broke docs generation for us. Checking what went wrong at http://api.cocoadocs.org:4567/error/Primer/3.0.0-beta.5 reveals this:
```
report_error({"message":"(<unknown>): did not find expected key while parsing a block mapping at line 1 column 1","trace":["/Users/cocoadocs/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/psych.rb:370:in `parse'","/Users/cocoadocs/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/psych.rb:370:in `parse_stream'","/Users/cocoadocs/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/psych.rb:318:in `parse'","/Users/cocoadocs/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/psych.rb:245:in `load'","/Users/cocoadocs/cocoadocs.org/classes/guides_generator.rb:64:in `cocoadocs_settings'","/Users/cocoadocs/cocoadocs.org/classes/guides_generator.rb:8:in `generate_array_for_appledoc'","/Users/cocoadocs/cocoadocs.org/classes/docset_generator.rb:54:in `docset_command'","/Users/cocoadocs/cocoadocs.org/classes/docset_generator.rb:74:in `create_docset'","/Users/cocoadocs/cocoadocs.org/./cocoadocs.rb:470:in `document_spec'","/Users/cocoadocs/cocoadocs.org/./cocoadocs.rb:541:in `document_spec_at_path'","/Users/cocoadocs/cocoadocs.org/./cocoadocs.rb:165:in `block in doc'","/Users/cocoadocs/cocoadocs.org/./cocoadocs.rb:160:in `each'","/Users/cocoadocs/cocoadocs.org/./cocoadocs.rb:160:in `doc'","/Users/cocoadocs/cocoadocs.org/./cocoadocs.rb:232:in `block in cocoadocs_url'","/Users/cocoadocs/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/open-uri.rb:153:in `open_uri'","/Users/cocoadocs/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/open-uri.rb:704:in `open'","/Users/cocoadocs/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/open-uri.rb:34:in `open'","/Users/cocoadocs/cocoadocs.org/./cocoadocs.rb:229:in `cocoadocs_url'","/Users/cocoadocs/cocoadocs.org/./cocoadocs.rb:180:in `cocoadocs'","/Users/cocoadocs/cocoadocs.org/./cocoadocs.rb:115:in `initialize'","/Users/cocoadocs/cocoadocs.org/./cocoadocs.rb:573:in `new'","/Users/cocoadocs/cocoadocs.org/./cocoadocs.rb:573:in `<main>'"]})
```

We tried to debug this by previewing the docs locally (as described on http://cocoadocs.org/readme/), but everything works perfectly, docs are even styled as expected.

**Comment by orta** [comment]
assuming this was a syntax error in the yaml - everything looks to be working

**Comment by Damol** [comment]
@orta It was either that or some setup issue, I don't recall. We somehow solved it a couple days later, apologies for not closing this back then, and thank you for handling it now. 👍
