### ISSUE TITLE
nil in testing idealist

### ISSUE THREAD

**Issue by orta** [CocoaPods/cocoadocs.org#446]
With: `bundle exec rake doc["iCarousel"]`

``` sh
Generating CLOC stats
vendor/cloc-1.62.pl --yaml --quiet /Users/cocoadocs/cocoadocs.org/activity/download/iCarousel/1.8.2/iCarousel/iCarousel/iCarousel.h /Users/cocoadocs/cocoadocs.org/activity/download/iCarousel/1.8.2/iCarousel/iCarousel/iCarousel.m
--------------/Users/cocoadocs/cocoadocs.org/activity/cocoadocs_specs/Specs/iCarousel/1.8.2/iCarousel.podspec.json-------------
undefined method `+' for nil:NilClass
------
["/Users/cocoadocs/cocoadocs.org/classes/testing_idealist.rb:40:in `block in testimate'", "/Users/cocoadocs/cocoadocs.org/classes/testing_idealist.rb:16:in `each'", "/Users/cocoadocs/cocoadocs.org/classes/testing_idealist.rb:16:in `reduce'", "/Users/cocoadocs/cocoadocs.org/classes/testing_idealist.rb:16:in `testimate'", "cocoadocs.rb:472:in `document_spec'", "cocoadocs.rb:535:in `document_spec_with_name'", "cocoadocs.rb:154:in `block in doc'", "cocoadocs.rb:147:in `each'", "cocoadocs.rb:147:in `doc'", "cocoadocs.rb:203:in `cocoadocs_doc'", "cocoadocs.rb:163:in `cocoadocs'", "cocoadocs.rb:102:in `initialize'", "cocoadocs.rb:560:in `new'", "cocoadocs.rb:560:in `<main>'"]
* - http://cocoadocs.org/docsets/iCarousel/1.8.2/
```

**Comment by orta** [comment]
Somehow there's a `nil` getting into here:

```
      expectations + find_test_target(project).reduce(0) do |target_expectations, target|
        files = get_source_files_for_target target

        target_estimate = files.map do |file|
          estimate_testingness_in_file file
        end.select do |estimate_hash|
          estimate_hash[:has_tests]
        end.reduce(0) do |num, hash|
          num + hash[:expectations]
        end

        puts "Found #{target_estimate} for #{target}"

        target_expectations + target_estimate
      end
    end
```

perhaps it needs a flatmap somewhere?
