### ISSUE TITLE
Error parsing new beta version of library: Non existent foler

### ISSUE THREAD

**Issue by SanjoDeundiak** [CocoaPods/cocoadocs.org#479]
My pod lives here https://github.com/VirgilSecurity/virgil-sdk-x/tree/4.0.0-beta7
I had no problems with cocoadocs till version 4.0.0-beta1, but there is no documentation for my framework since that version. I tried to redeploy latest version (4.0.0-beta7), and I get this error:

<pre>{
  "message": "\u001b[31m[!] Attempt to read non existent folder `/Users/cocoadocs/cocoadocs.org/activity/download/VirgilSDK/4.0.0-beta7/VirgilSDK`.\u001b[0m",
  "trace": [
    "/Users/cocoadocs/.rvm/gems/ruby-2.1.3/gems/cocoapods-1.0.1/lib/cocoapods/sandbox/path_list.rb:51:in `read_file_system'",
    "/Users/cocoadocs/.rvm/gems/ruby-2.1.3/gems/cocoapods-1.0.1/lib/cocoapods/sandbox/path_list.rb:34:in `files'",
    "/Users/cocoadocs/.rvm/gems/ruby-2.1.3/gems/cocoapods-1.0.1/lib/cocoapods/sandbox/path_list.rb:117:in `relative_glob'",
    "/Users/cocoadocs/.rvm/gems/ruby-2.1.3/gems/cocoapods-1.0.1/lib/cocoapods/sandbox/path_list.rb:79:in `glob'",
    "/Users/cocoadocs/.rvm/gems/ruby-2.1.3/gems/cocoapods-1.0.1/lib/cocoapods/sandbox/file_accessor.rb:363:in `expanded_paths'",
    "/Users/cocoadocs/.rvm/gems/ruby-2.1.3/gems/cocoapods-1.0.1/lib/cocoapods/sandbox/file_accessor.rb:334:in `paths_for_attribute'",
    "/Users/cocoadocs/.rvm/gems/ruby-2.1.3/gems/cocoapods-1.0.1/lib/cocoapods/sandbox/file_accessor.rb:302:in `public_header_files'",
    "/Users/cocoadocs/.rvm/gems/ruby-2.1.3/gems/cocoapods-1.0.1/lib/cocoapods/sandbox/file_accessor.rb:119:in `public_headers'",
    "/Users/cocoadocs/cocoadocs.org/classes/docset_generator.rb:134:in `block (2 levels) in headers_for_spec_at_location'",
    "/Users/cocoadocs/cocoadocs.org/classes/docset_generator.rb:130:in `each'",
    "/Users/cocoadocs/cocoadocs.org/classes/docset_generator.rb:130:in `block in headers_for_spec_at_location'",
    "/Users/cocoadocs/cocoadocs.org/classes/docset_generator.rb:129:in `each'",
    "/Users/cocoadocs/cocoadocs.org/classes/docset_generator.rb:129:in `headers_for_spec_at_location'",
    "/Users/cocoadocs/cocoadocs.org/classes/docset_generator.rb:16:in `docset_command'",
    "/Users/cocoadocs/cocoadocs.org/classes/docset_generator.rb:74:in `create_docset'",
    "/Users/cocoadocs/cocoadocs.org/./cocoadocs.rb:458:in `document_spec'",
    "/Users/cocoadocs/cocoadocs.org/./cocoadocs.rb:529:in `document_spec_at_path'",
    "/Users/cocoadocs/cocoadocs.org/./cocoadocs.rb:152:in `block in doc'",
    "/Users/cocoadocs/cocoadocs.org/./cocoadocs.rb:147:in `each'",
    "/Users/cocoadocs/cocoadocs.org/./cocoadocs.rb:147:in `doc'",
    "/Users/cocoadocs/cocoadocs.org/./cocoadocs.rb:219:in `block in cocoadocs_url'",
    "/Users/cocoadocs/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/open-uri.rb:153:in `open_uri'",
    "/Users/cocoadocs/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/open-uri.rb:704:in `open'",
    "/Users/cocoadocs/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/open-uri.rb:34:in `open'",
    "/Users/cocoadocs/cocoadocs.org/./cocoadocs.rb:216:in `cocoadocs_url'",
    "/Users/cocoadocs/cocoadocs.org/./cocoadocs.rb:167:in `cocoadocs'",
    "/Users/cocoadocs/cocoadocs.org/./cocoadocs.rb:102:in `initialize'",
    "/Users/cocoadocs/cocoadocs.org/./cocoadocs.rb:561:in `new'",
    "/Users/cocoadocs/cocoadocs.org/./cocoadocs.rb:561:in `<main>'"
  ]
}</pre>

**Comment by SanjoDeundiak** [comment]
Seems like after I manually went to url http://cocoadocs.org/docsets/VirgilSDK/4.0.0-beta7/ web UI updated and now I can see all versions in dropdown menu. Anyway, error message that I get using HTTP request on http://api.cocoadocs.org:4567/error/VirgilSDK/4.0.0-beta7 is unclear for me
