### ISSUE TITLE
Expand option not available for SwiftResponsiveLabel

### ISSUE THREAD

**Issue by hsusmita** [CocoaPods/cocoadocs.org#480]
**http://cocoadocs.org/docsets/SwiftResponsiveLabel/1.1/** works fine
 **http://api.cocoadocs.org:4567/redeploy/SwiftResponsiveLabel/latest** returns parsing true.
  **http://api.cocoadocs.org:4567/error/SwiftResponsiveLabel/1.1** returns the following error.
```
report_error({"message":"undefined method `strip' for nil:NilClass","trace":["/Users/cocoadocs/cocoadocs.org/./cocoadocs.rb:429:in `block in document_spec'","/Users/cocoadocs/cocoadocs.org/./cocoadocs.rb:416:in `tap'","/Users/cocoadocs/cocoadocs.org/./cocoadocs.rb:416:in `document_spec'","/Users/cocoadocs/cocoadocs.org/./cocoadocs.rb:532:in `document_spec_at_path'","/Users/cocoadocs/cocoadocs.org/./cocoadocs.rb:152:in `block in doc'","/Users/cocoadocs/cocoadocs.org/./cocoadocs.rb:147:in `each'","/Users/cocoadocs/cocoadocs.org/./cocoadocs.rb:147:in `doc'","/Users/cocoadocs/cocoadocs.org/./cocoadocs.rb:219:in `block in cocoadocs_url'","/Users/cocoadocs/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/open-uri.rb:153:in `open_uri'","/Users/cocoadocs/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/open-uri.rb:704:in `open'","/Users/cocoadocs/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/open-uri.rb:34:in `open'","/Users/cocoadocs/cocoadocs.org/./cocoadocs.rb:216:in `cocoadocs_url'","/Users/cocoadocs/cocoadocs.org/./cocoadocs.rb:167:in `cocoadocs'","/Users/cocoadocs/cocoadocs.org/./cocoadocs.rb:102:in `initialize'","/Users/cocoadocs/cocoadocs.org/./cocoadocs.rb:564:in `new'","/Users/cocoadocs/cocoadocs.org/./cocoadocs.rb:564:in `<main>'"]}
```

**Comment by orta** [comment]
Should be fixed by https://github.com/CocoaPods/cocoadocs.org/commit/90e1d9379bec104b73f0bcb121bedfdb6fb242cc

**Comment by orta** [comment]
Confirmed: http://cocoapods.org/pods/SwiftResponsiveLabel
