### ISSUE TITLE
Jazzy errors with Swift 2.3

### ISSUE THREAD

**Issue by mattrubin** [CocoaPods/cocoadocs.org#484]
[CocoaDocs for OneTimePassword 2.1](http://cocoadocs.org/docsets/OneTimePassword/2.1/) (an all-Swift pod) appears as 0% documented, and shows references for only an Objective-C class used in a test target. CocoaDocs has [previously](http://cocoadocs.org/docsets/OneTimePassword/2.0.1/) built the docs without a problem.

Visiting [the errors page](http://api.cocoadocs.org:4567/error/OneTimePassword/2.1) for the pod, I see the following (formatted below for readability):
```javascript
report_error({
  "message": "Unable to find an Xcode with swift version 2.3.",
  "trace": [
    "/Users/cocoadocs/.rvm/gems/ruby-2.1.3/bundler/gems/Jazzy-7242435d5756/lib/jazzy/sourcekitten.rb:140:in `run_sourcekitten'",
    "/Users/cocoadocs/.rvm/gems/ruby-2.1.3/bundler/gems/Jazzy-7242435d5756/lib/jazzy/podspec_documenter.rb:31:in `block (3 levels) in sourcekitten_output'",
    "/Users/cocoadocs/.rvm/gems/ruby-2.1.3/bundler/gems/Jazzy-7242435d5756/lib/jazzy/podspec_documenter.rb:26:in `map'",
    "/Users/cocoadocs/.rvm/gems/ruby-2.1.3/bundler/gems/Jazzy-7242435d5756/lib/jazzy/podspec_documenter.rb:26:in `block (2 levels) in sourcekitten_output'",
    "/Users/cocoadocs/.rvm/gems/ruby-2.1.3/gems/xcodeproj-1.3.3/lib/xcodeproj/plist/ffi/chdir_override.rb:13:in `cp_chdir'",
    "/Users/cocoadocs/.rvm/gems/ruby-2.1.3/bundler/gems/Jazzy-7242435d5756/lib/jazzy/podspec_documenter.rb:21:in `block in sourcekitten_output'",
    "/Users/cocoadocs/.rvm/gems/ruby-2.1.3/gems/cocoapods-1.1.1/lib/cocoapods/config.rb:41:in `with_changes'",
    "/Users/cocoadocs/.rvm/gems/ruby-2.1.3/bundler/gems/Jazzy-7242435d5756/lib/jazzy/podspec_documenter.rb:17:in `sourcekitten_output'",
    "/Users/cocoadocs/.rvm/gems/ruby-2.1.3/bundler/gems/Jazzy-7242435d5756/lib/jazzy/doc_builder.rb:61:in `build'",
    "/Users/cocoadocs/cocoadocs.org/./cocoadocs.rb:443:in `document_spec'",
    "/Users/cocoadocs/cocoadocs.org/./cocoadocs.rb:532:in `document_spec_at_path'",
    "/Users/cocoadocs/cocoadocs.org/./cocoadocs.rb:152:in `block in doc'",
    "/Users/cocoadocs/cocoadocs.org/./cocoadocs.rb:147:in `each'",
    "/Users/cocoadocs/cocoadocs.org/./cocoadocs.rb:147:in `doc'",
    "/Users/cocoadocs/cocoadocs.org/./cocoadocs.rb:219:in `block in cocoadocs_url'",
    "/Users/cocoadocs/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/open-uri.rb:153:in `open_uri'",
    "/Users/cocoadocs/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/open-uri.rb:704:in `open'",
    "/Users/cocoadocs/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/open-uri.rb:34:in `open'",
    "/Users/cocoadocs/cocoadocs.org/./cocoadocs.rb:216:in `cocoadocs_url'",
    "/Users/cocoadocs/cocoadocs.org/./cocoadocs.rb:167:in `cocoadocs'",
    "/Users/cocoadocs/cocoadocs.org/./cocoadocs.rb:102:in `initialize'",
    "/Users/cocoadocs/cocoadocs.org/./cocoadocs.rb:564:in `new'",
    "/Users/cocoadocs/cocoadocs.org/./cocoadocs.rb:564:in `<main>'"
  ]
})
```

The library is in Swift 2.3, and indicates this both in the .xcodeproj settings and a .swift-version file. Looking at [similar issues with Jazzy](https://github.com/realm/jazzy/issues?utf8=✓&q=%22Unable%20to%20find%20an%20Xcode%20with%20swift%20version%22%20), it seems this sort of error is often caused by using the wrong version of Xcode, or requesting the wrong Swift version. Swift 2.3 is the correct language version, so is it possible CocoaDocs is attempting to use a version of Xcode (pre-8.0) which doesn't have Swift 2.3 support?

**Comment by orta** [comment]
It shouldn't we have Xcode 8.1 on I think, so that we support Swift 3.0 - could be an issue with finding the version number, aye

**Comment by FabrizioBrancati** [comment]
I think this issue is related to #493 because OneTimePassword also has a [.swift-version](https://github.com/mattrubin/OneTimePassword/blob/develop/.swift-version) file with `2.3` as Swift version.

**Comment by orta** [comment]
I'm not supporting old Xcode's, perhaps BuddyBuild's setup would support multiple Xcode's - but 1 Xcode is enough effort for my dwindling spare time.
