### ISSUE TITLE
CocoaDocs uses AppleDoc instead of Jazzy for BFKit-Swift docs (.swift-version) 

### ISSUE THREAD

**Issue by FabrizioBrancati** [CocoaPods/cocoadocs.org#493]
I've just released 2.0.0 version of my [BFKit-Swift](https://github.com/FabrizioBrancati/BFKit-Swift/) library, but [CocoaDocs](http://cocoadocs.org/docsets/BFKit-Swift/2.0.0/) seem to parsing it as an Objective-C pod.

Checking the error type with [API](http://api.cocoadocs.org:4567/error/BFKit-Swift/2.0.0) it shows that it was "Unable to find an Xcode with swift version 3.0.1."

Maybe this is because my library support both Linux and iOS, so it has a [.swift-version](https://github.com/FabrizioBrancati/BFKit-Swift/blob/master/.swift-version) file with `3.0.1` Swift version, and SourceKitten has `3.0` into its [.swift-version](https://github.com/jpsim/SourceKitten/blob/master/.swift-version) file.

**Comment by onevcat** [comment]
Similar issue here for my repo [Kingfisher](https://github.com/onevcat/Kingfisher), but with a different error:

```js
{
  "message": "comparison of Array with Array failed",
  "trace": [
    "/Users/cocoadocs/.rvm/gems/ruby-2.1.3/bundler/gems/Jazzy-7242435d5756/lib/jazzy/doc_builder.rb:35:in `sort_by'",
    "/Users/cocoadocs/.rvm/gems/ruby-2.1.3/bundler/gems/Jazzy-7242435d5756/lib/jazzy/doc_builder.rb:35:in `block in doc_structure_for_docs'",
    "/Users/cocoadocs/.rvm/gems/ruby-2.1.3/bundler/gems/Jazzy-7242435d5756/lib/jazzy/doc_builder.rb:33:in `map'",
    "/Users/cocoadocs/.rvm/gems/ruby-2.1.3/bundler/gems/Jazzy-7242435d5756/lib/jazzy/doc_builder.rb:33:in `doc_structure_for_docs'",
    "/Users/cocoadocs/.rvm/gems/ruby-2.1.3/bundler/gems/Jazzy-7242435d5756/lib/jazzy/doc_builder.rb:113:in `build_site'",
    "/Users/cocoadocs/.rvm/gems/ruby-2.1.3/bundler/gems/Jazzy-7242435d5756/lib/jazzy/doc_builder.rb:152:in `build_docs_for_sourcekitten_output'",
    "/Users/cocoadocs/.rvm/gems/ruby-2.1.3/bundler/gems/Jazzy-7242435d5756/lib/jazzy/doc_builder.rb:76:in `build'",
    "/Users/cocoadocs/cocoadocs.org/./cocoadocs.rb:443:in `document_spec'",
    "/Users/cocoadocs/cocoadocs.org/./cocoadocs.rb:532:in `document_spec_at_path'",
    "/Users/cocoadocs/cocoadocs.org/./cocoadocs.rb:152:in `block in doc'",
    "/Users/cocoadocs/cocoadocs.org/./cocoadocs.rb:147:in `each'",
    "/Users/cocoadocs/cocoadocs.org/./cocoadocs.rb:147:in `doc'",
    "/Users/cocoadocs/cocoadocs.org/./cocoadocs.rb:219:in `block in cocoadocs_url'",
    "/Users/cocoadocs/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/open-uri.rb:153:in `open_uri'",
    "/Users/cocoadocs/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/open-uri.rb:704:in `open'",
    "/Users/cocoadocs/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/open-uri.rb:34:in `open'",
    "/Users/cocoadocs/cocoadocs.org/./cocoadocs.rb:216:in `cocoadocs_url'",
    "/Users/cocoadocs/cocoadocs.org/./cocoadocs.rb:167:in `cocoadocs'",
    "/Users/cocoadocs/cocoadocs.org/./cocoadocs.rb:102:in `initialize'",
    "/Users/cocoadocs/cocoadocs.org/./cocoadocs.rb:564:in `new'",
    "/Users/cocoadocs/cocoadocs.org/./cocoadocs.rb:564:in `<main>'"
  ]
}
```

And it seems that some other Swift docs (like [Alamofire](http://cocoadocs.org/docsets/Alamofire/4.2.0/)) generated after Nov (for me, after 7th, Nov) is recognized as Objective-C project too. However, when I tried to generate the docs locally with jazzy 0.7.3, everything works fine.

**Comment by onevcat** [comment]
Oops, I missed #489 

After regenerating the doc, everything gets fixed for me.

**Comment by indisoluble** [comment]
Hi there,

No matter what I do, I can not get CocoaDoc to generate the documentation for my project. More exactly, it parses my library: https://cocoapods.org/pods/HRLClassifier, with AppleDoc instead of Jazzy, although the main language of my library is Swift.

I forced a re-parse of the library (http://api.cocoadocs.org:4567/redeploy/HRLClassifier/0.1.4) with no success. This is the error I got (http://api.cocoadocs.org:4567/error/HRLClassifier/0.1.4):

```
report_error({"message":"\u001b[31m[!] Unable to find a specification for `HRLAlgorithms (~> 0.1)` depended upon by `HRLClassifier`\u001b[0m","trace":["/Users/cocoadocs/.rvm/gems/ruby-2.1.3/gems/cocoapods-1.1.1/lib/cocoapods/resolver.rb:442:in `handle_resolver_error'","/Users/cocoadocs/.rvm/gems/ruby-2.1.3/gems/cocoapods-1.1.1/lib/cocoapods/resolver.rb:65:in `rescue in resolve'","/Users/cocoadocs/.rvm/gems/ruby-2.1.3/gems/cocoapods-1.1.1/lib/cocoapods/resolver.rb:57:in `resolve'","/Users/cocoadocs/.rvm/gems/ruby-2.1.3/gems/cocoapods-1.1.1/lib/cocoapods/installer/analyzer.rb:723:in `block in resolve_dependencies'","/Users/cocoadocs/.rvm/gems/ruby-2.1.3/gems/cocoapods-1.1.1/lib/cocoapods/user_interface.rb:64:in `section'","/Users/cocoadocs/.rvm/gems/ruby-2.1.3/gems/cocoapods-1.1.1/lib/cocoapods/installer/analyzer.rb:721:in `resolve_dependencies'","/Users/cocoadocs/.rvm/gems/ruby-2.1.3/gems/cocoapods-1.1.1/lib/cocoapods/installer/analyzer.rb:76:in `analyze'","/Users/cocoadocs/.rvm/gems/ruby-2.1.3/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:236:in `analyze'","/Users/cocoadocs/.rvm/gems/ruby-2.1.3/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:150:in `block in resolve_dependencies'","/Users/cocoadocs/.rvm/gems/ruby-2.1.3/gems/cocoapods-1.1.1/lib/cocoapods/user_interface.rb:64:in `section'","/Users/cocoadocs/.rvm/gems/ruby-2.1.3/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:149:in `resolve_dependencies'","/Users/cocoadocs/.rvm/gems/ruby-2.1.3/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:110:in `install!'","/Users/cocoadocs/.rvm/gems/ruby-2.1.3/bundler/gems/Jazzy-7e752d129a76/lib/jazzy/podspec_documenter.rb:20:in `block in sourcekitten_output'","/Users/cocoadocs/.rvm/gems/ruby-2.1.3/gems/cocoapods-1.1.1/lib/cocoapods/config.rb:41:in `with_changes'","/Users/cocoadocs/.rvm/gems/ruby-2.1.3/bundler/gems/Jazzy-7e752d129a76/lib/jazzy/podspec_documenter.rb:17:in `sourcekitten_output'","/Users/cocoadocs/.rvm/gems/ruby-2.1.3/bundler/gems/Jazzy-7e752d129a76/lib/jazzy/doc_builder.rb:61:in `build'","/Users/cocoadocs/cocoadocs.org/./cocoadocs.rb:431:in `document_spec'","/Users/cocoadocs/cocoadocs.org/./cocoadocs.rb:520:in `document_spec_at_path'","/Users/cocoadocs/cocoadocs.org/./cocoadocs.rb:152:in `block in doc'","/Users/cocoadocs/cocoadocs.org/./cocoadocs.rb:147:in `each'","/Users/cocoadocs/cocoadocs.org/./cocoadocs.rb:147:in `doc'","/Users/cocoadocs/cocoadocs.org/./cocoadocs.rb:219:in `block in cocoadocs_url'","/Users/cocoadocs/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/open-uri.rb:153:in `open_uri'","/Users/cocoadocs/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/open-uri.rb:704:in `open'","/Users/cocoadocs/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/open-uri.rb:34:in `open'","/Users/cocoadocs/cocoadocs.org/./cocoadocs.rb:216:in `cocoadocs_url'","/Users/cocoadocs/cocoadocs.org/./cocoadocs.rb:167:in `cocoadocs'","/Users/cocoadocs/cocoadocs.org/./cocoadocs.rb:102:in `initialize'","/Users/cocoadocs/cocoadocs.org/./cocoadocs.rb:552:in `new'","/Users/cocoadocs/cocoadocs.org/./cocoadocs.rb:552:in `<main>'"]}
)
```

Is there anything I can do to solve this problem? Regards.
