### ISSUE TITLE
New pod not generating page on CocoaPods.org (AVPlayerItemHomeOutput)

### ISSUE THREAD

**Issue by alexruperez** [CocoaPods/cocoadocs.org#519]
"Finally, if there's nothing specific to your problem, delete this template and start your issue." :+1:

[AVPlayerItemHomeOutput](http://cocoadocs.org/docsets/AVPlayerItemHomeOutput) don't generate CocoaPods.org page. 😞 

Thanks! 😃

**Comment by Decybel07** [comment]
I have this same problem with my [L10n-swift](http://cocoapods.org/pods/L10n-swift)

**Comment by ulukaya** [comment]
Having same issue on DigitsMigrationHelper

**Comment by davidair** [comment]
Same for TensorFlow-experimental and FirebasePerformance

**Comment by mylyuic** [comment]
also a problem for Digits

**Comment by orta** [comment]
Fixed by #508 

* http://cocoadocs.org/docsets/AVPlayerItemHomeOutput/0.1.5/
* http://cocoadocs.org/docsets/L10n-swift/2.0.2/
* http://cocoadocs.org/docsets/DigitsMigrationHelper/0.1.0/
* http://cocoadocs.org/docsets/FirebasePerformance/1.0.0/
* http://cocoadocs.org/docsets/Digits/3.0.0/

Not fixed: TensorFlow-experiemental

```
04:06:08 web.1      | - -> /redeploy/TensorFlow-experimental/latest
04:06:12 web.1      |
04:06:12 web.1      |  Looking at TensorFlow-experimental 1.1.0
04:06:12 web.1      |
04:06:12 web.1      |  > Http download
04:06:35 web.1      | Errno::ENOENT: No such file or directory @ rb_sysopen - /Users/cocoadocs/cocoadocs.org/activity/docsets/TensorFlow-experimental/1.1.0//com.cocoadocs.tensorflow-experimental.TensorFlow-experimental.docset/Contents/Resources/Documents/appledoc_stylesheet.css
04:06:35 web.1      |   Use --trace for backtrace.
04:06:35 web.1      | sass views/appledoc_stylesheet.scss:"/Users/cocoadocs/cocoadocs.org/activity/docsets/TensorFlow-experimental/1.1.0/"/com.cocoadocs.tensorflow-experimental.TensorFlow-experimental.docset/Contents/Resources/Documents/appledoc_stylesheet.css failed!
04:06:36 web.1      | Errno::ENOENT: No such file or directory @ rb_sysopen - /Users/cocoadocs/cocoadocs.org/activity/docsets/TensorFlow-experimental/1.1.0//com.cocoadocs.tensorflow-experimental.TensorFlow-experimental.docset/Contents/Resources/Documents/appledoc_gfm.css
04:06:36 web.1      |   Use --trace for backtrace.
04:06:36 web.1      | sass views/appledoc_gfm.scss:"/Users/cocoadocs/cocoadocs.org/activity/docsets/TensorFlow-experimental/1.1.0/"/com.cocoadocs.tensorflow-experimental.TensorFlow-experimental.docset/Contents/Resources/Documents/appledoc_gfm.css failed!
04:06:36 web.1      | cp: /Users/cocoadocs/cocoadocs.org/activity/docsets/TensorFlow-experimental/1.1.0//com.cocoadocs.tensorflow-experimental.TensorFlow-experimental.docset/Contents/Resources/Documents/appledoc_stylesheet.css: No such file or directory
04:06:36 web.1      | cp "/Users/cocoadocs/cocoadocs.org/activity/docsets/TensorFlow-experimental/1.1.0/"/com.cocoadocs.tensorflow-experimental.TensorFlow-experimental.docset/Contents/Resources/Documents/appledoc_stylesheet.css "/Users/cocoadocs/cocoadocs.org/activity/docsets/TensorFlow-experimental/1.1.0//" failed!
04:06:36 web.1      | cp: /Users/cocoadocs/cocoadocs.org/activity/docsets/TensorFlow-experimental/1.1.0//com.cocoadocs.tensorflow-experimental.TensorFlow-experimental.docset/Contents/Resources/Documents/appledoc_gfm.css: No such file or directory
04:06:36 web.1      | cp "/Users/cocoadocs/cocoadocs.org/activity/docsets/TensorFlow-experimental/1.1.0/"/com.cocoadocs.tensorflow-experimental.TensorFlow-experimental.docset/Contents/Resources/Documents/appledoc_gfm.css "/Users/cocoadocs/cocoadocs.org/activity/docsets/TensorFlow-experimental/1.1.0//" failed!
04:06:36 web.1      | cp: /Users/cocoadocs/cocoadocs.org/activity/docsets/TensorFlow-experimental/1.1.0//com.cocoadocs.tensorflow-experimental.TensorFlow-experimental.docset/icon.png: No such file or directory
04:06:36 web.1      | cp resources/docset_icon.png "/Users/cocoadocs/cocoadocs.org/activity/docsets/TensorFlow-experimental/1.1.0/"/com.cocoadocs.tensorflow-experimental.TensorFlow-experimental.docset/icon.png failed!
04:06:36 web.1      | --------------/Users/cocoadocs/cocoadocs.org/activity/podspecs/TensorFlow-experimental.podspec.json-------------
04:06:36 web.1      | unable to open database file
04:06:36 web.1      | ------
04:06:36 web.1      | ["/Users/cocoadocs/.rvm/gems/ruby-2.1.3/gems/docstat-1.0.4/lib/docstat/container.rb:25:in `initialize'", "/Users/cocoadocs/.rvm/gems/ruby-2.1.3/gems/docstat-1.0.4/lib/docstat/container.rb:25:in `new'", "/Users/cocoadocs/.rvm/gems/ruby-2.1.3/gems/docstat-1.0.4/lib/docstat/container.rb:25:in `from_sqlite'", "/Users/cocoadocs/.rvm/gems/ruby-2.1.3/gems/docstat-1.0.4/lib/docstat.rb:48:in `containers_from_docset'", "/Users/cocoadocs/.rvm/gems/ruby-2.1.3/gems/docstat-1.0.4/lib/docstat.rb:33:in `process'", "/Users/cocoadocs/cocoadocs.org/classes/docset_fixer.rb:86:in `get_doc_percent'", "/Users/cocoadocs/cocoadocs.org/classes/docset_fixer.rb:55:in `post_process'", "/Users/cocoadocs/cocoadocs.org/classes/docset_fixer.rb:21:in `fix'", "/Users/cocoadocs/cocoadocs.org/./cocoadocs.rb:451:in `document_spec'", "/Users/cocoadocs/cocoadocs.org/./cocoadocs.rb:520:in `document_spec_at_path'", "/Users/cocoadocs/cocoadocs.org/./cocoadocs.rb:152:in `block in doc'", "/Users/cocoadocs/cocoadocs.org/./cocoadocs.rb:147:in `each'", "/Users/cocoadocs/cocoadocs.org/./cocoadocs.rb:147:in `doc'", "/Users/cocoadocs/cocoadocs.org/./cocoadocs.rb:219:in `block in cocoadocs_url'", "/Users/cocoadocs/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/open-uri.rb:153:in `open_uri'", "/Users/cocoadocs/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/open-uri.rb:704:in `open'", "/Users/cocoadocs/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/open-uri.rb:34:in `open'", "/Users/cocoadocs/cocoadocs.org/./cocoadocs.rb:216:in `cocoadocs_url'", "/Users/cocoadocs/cocoadocs.org/./cocoadocs.rb:167:in `cocoadocs'", "/Users/cocoadocs/cocoadocs.org/./cocoadocs.rb:102:in `initialize'", "/Users/cocoadocs/cocoadocs.org/./cocoadocs.rb:552:in `new'", "/Users/cocoadocs/cocoadocs.org/./cocoadocs.rb:552:in `<main>'"]
```

Interesting appledoc error on Digits, didn't break the build though:

```
04:08:10 web.1      |  Looking at Digits 3.0.0
04:08:10 web.1      |
04:08:10 web.1      |  > Http download
04:08:25 web.1      | ERROR | !> 2017-05-20 04:08:25.234 docsetutil[21083:3658830] Loading legacy model docSet_v8
04:08:25 web.1      | ERROR | !> 2017-05-20 04:08:25.261 docsetutil[21083:3658830] Saving managed object context
04:08:25 web.1      | ERROR | !> 2017-05-20 04:08:25.264 docsetutil[21083:3658830] Successfully loaded Digits Documentation 3.0.0
04:08:25 web.1      | ERROR | !> 2017-05-20 04:08:25.265 docsetutil[21083:3658830] migrate data to: /Users/cocoadocs/cocoadocs.org/activity/docsets/Digits/3.0.0/docset/Contents/Resources/docSet.dsidx
04:08:26 web.1      | ERROR | !> 2017-05-20 04:08:26.221 docsetutil[21083:3658830] Saving managed object context
04:08:26 web.1      | ERROR | !> 2017-05-20 04:08:26.435 docsetutil[21083:3658830] Loading legacy model docSet_v8
04:08:26 web.1      | ERROR | !> 2017-05-20 04:08:26.893 docsetutil[21083:3658830] Load mappings:  0.000
04:08:27 web.1      | ERROR | !> 2017-05-20 04:08:27.038 docsetutil[21083:3658830] New __DEFAULT__ = 1 (docset: __DEFAULT__)
04:08:28 web.1      | ERROR | !> 2017-05-20 04:08:28.836 docsetutil[21083:3658830] Saving managed object context
04:08:29 web.1      | ERROR | !> 2017-05-20 04:08:29.726 docsetutil[21086:3658874] Successfully loaded Digits Documentation 3.0.0
04:08:30 web.1      | appledoc version: 2.2.1 (build 1333)
04:08:30 web.1      |
04:08:30 web.1      | Generation step 4/4 failed: GBDocSetPublishGenerator failed generating output, aborting!
04:08:30 web.1      | docsetutil failed to package the documentation set!
04:08:30 web.1      | 2017-05-20 04:08:29.726 docsetutil[21086:3658874] Successfully loaded Digits Documentation 3.0.0
```

**Comment by alexruperez** [comment]
Thanks @orta! 👍

**Comment by davidair** [comment]
It looks like the docset_generator fails for TensorFlow-experimental because it has too many header files (so the command-line to vendor/appledoc is massive). Is the docset required to generate the pod home page?

**Comment by orta** [comment]
@davidair - yes! This is the exact kind of reason I split the two: http://cocoapods.org/pods/TensorFlow-experimental

( It won't show up as available in search for a day or two )
