### ISSUE TITLE
GitHub rendering README issue?

### ISSUE THREAD

**Issue by orta** [CocoaPods/cocoadocs.org#522]
When looking at CJPopupView (saw it on multiple versions of this lib)
```
05:25:03 web.1      |
05:25:03 web.1      |  > Git download
05:25:05 web.1      | --------------CJPopupView (2.0.4)-------------
05:25:05 web.1      | "\xE5" on US-ASCII
05:25:05 web.1      | ------
05:25:05 web.1      | ["/Users/cocoadocs/.rvm/gems/ruby-2.1.3/gems/multi_json-1.10.1/lib/multi_json/adapters/json_common.rb:21:in `encode'", "/Users/cocoadocs/.rvm/gems/ruby-2.1.3/gems/multi_json-1.10.1/lib/multi_json/adapters/json_common.rb:21:in `to_json'", "/Users/cocoadocs/.rvm/gems/ruby-2.1.3/gems/multi_json-1.10.1/lib/multi_json/adapters/json_common.rb:21:in `dump'", "/Users/cocoadocs/.rvm/gems/ruby-2.1.3/gems/multi_json-1.10.1/lib/multi_json/adapter.rb:24:in `dump'", "/Users/cocoadocs/.rvm/gems/ruby-2.1.3/gems/multi_json-1.10.1/lib/multi_json.rb:136:in `dump'", "/Users/cocoadocs/.rvm/gems/ruby-2.1.3/gems/sawyer-0.5.5/lib/sawyer/serializer.rb:49:in `call'", "/Users/cocoadocs/.rvm/gems/ruby-2.1.3/gems/sawyer-0.5.5/lib/sawyer/serializer.rb:49:in `encode'", "/Users/cocoadocs/.rvm/gems/ruby-2.1.3/gems/sawyer-0.5.5/lib/sawyer/agent.rb:116:in `encode_body'", "/Users/cocoadocs/.rvm/gems/ruby-2.1.3/gems/sawyer-0.5.5/lib/sawyer/agent.rb:96:in `block in call'", "/Users/cocoadocs/.rvm/gems/ruby-2.1.3/gems/faraday-0.9.0/lib/faraday/connection.rb:374:in `block in run_request'", "/Users/cocoadocs/.rvm/gems/ruby-2.1.3/gems/faraday-0.9.0/lib/faraday/connection.rb:388:in `block in build_request'", "/Users/cocoadocs/.rvm/gems/ruby-2.1.3/gems/faraday-0.9.0/lib/faraday/request.rb:26:in `block in create'", "/Users/cocoadocs/.rvm/gems/ruby-2.1.3/gems/faraday-0.9.0/lib/faraday/request.rb:25:in `tap'", "/Users/cocoadocs/.rvm/gems/ruby-2.1.3/gems/faraday-0.9.0/lib/faraday/request.rb:25:in `create'", "/Users/cocoadocs/.rvm/gems/ruby-2.1.3/gems/faraday-0.9.0/lib/faraday/connection.rb:384:in `build_request'", "/Users/cocoadocs/.rvm/gems/ruby-2.1.3/gems/faraday-0.9.0/lib/faraday/connection.rb:370:in `run_request'", "/Users/cocoadocs/.rvm/gems/ruby-2.1.3/gems/faraday-0.9.0/lib/faraday/connection.rb:177:in `post'", "/Users/cocoadocs/.rvm/gems/ruby-2.1.3/gems/sawyer-0.5.5/lib/sawyer/agent.rb:94:in `call'", "/Users/cocoadocs/.rvm/gems/ruby-2.1.3/gems/octokit-3.4.2/lib/octokit/client.rb:339:in `request'", "/Users/cocoadocs/.rvm/gems/ruby-2.1.3/gems/octokit-3.4.2/lib/octokit/client.rb:144:in `post'", "/Users/cocoadocs/.rvm/gems/ruby-2.1.3/gems/octokit-3.4.2/lib/octokit/client/markdown.rb:23:in `markdown'", "/Users/cocoadocs/.rvm/gems/ruby-2.1.3/gems/octokit-3.4.2/lib/octokit.rb:27:in `method_missing'", "/Users/cocoadocs/cocoadocs.org/classes/readme_generator.rb:37:in `github_render'", "/Users/cocoadocs/cocoadocs.org/classes/readme_generator.rb:23:in `create_readme'", "/Users/cocoadocs/cocoadocs.org/./cocoapods-simple.rb:73:in `run'", "/Users/cocoadocs/cocoadocs.org/./cocoapods-simple.rb:148:in `<main>'"]
```

**Comment by orta** [comment]
Works though: http://cocoadocs.org/docsets/CJPopupView/2.0.4/

**Comment by orta** [comment]
Fixed
