### ISSUE TITLE
CocoaDocs doesn't generate documentation for my project

### ISSUE THREAD

**Issue by edjiang** [CocoaPods/cocoadocs.org#540]
This is for UberRides 0.7.0. https://cocoapods.org/pods/UberRides

I've checked at http://cocoadocs.org/docsets/UberRides/0.7.0/. I get a 404. 

I tried using http://api.cocoadocs.org:4567/redeploy/UberRides/latest/. It responds with `{"parsing":true}`. No docs are generated.

I tried checking for errors using http://api.cocoadocs.org:4567/error/UberRides/0.7.0. It returns `{"message":"Could not find any errors, perhaps CocoaDocs has not ran the processing?", "trace" :[]}`

I tried cloning CocoaDocs, and ran `bundle exec ./cocoadocs.rb preview UberRides`. It generated documentation correctly.  

Is CocoaDocs on a temporary outage while things are being migrated as mentioned in #538?

**Comment by SanjithKanagavel** [comment]
@dnkoutso Please take a look here  https://github.com/CocoaPods/cocoapods.org/issues/334
Something similar is happening. 
Can you help me with some little better context why its happening.

**Comment by edjiang** [comment]
Closing since the problem seems to be fixed now.

**Comment by orta** [comment]
Oh yeah - it turned out the CocoaPods docs server had ran out of disk space, yesterday I went and deleted some build artifacts that have been around for the last ~5 years. So things are working again.

**Comment by edjiang** [comment]
Thanks @orta! 

Quick aside: I noticed that the documentation doesn't seem to be generating anything beyond the README; I noticed that the errors endpoint now says:

```
{
  "message": "\u001b[31m[!] Attempt to read non existent folder `\/Users\/cocoadocs\/cocoadocs.org\/activity\/download\/UberRides\/0.7.0\/UberRides`.\u001b[0m",
  "trace": [
    "\/Users\/cocoadocs\/.rvm\/gems\/ruby-2.1.3\/gems\/cocoapods-1.1.1\/lib\/cocoapods\/sandbox\/path_list.rb:51:in `read_file_system'",
    "\/Users\/cocoadocs\/.rvm\/gems\/ruby-2.1.3\/gems\/cocoapods-1.1.1\/lib\/cocoapods\/sandbox\/path_list.rb:34:in `files'",
    "\/Users\/cocoadocs\/.rvm\/gems\/ruby-2.1.3\/gems\/cocoapods-1.1.1\/lib\/cocoapods\/sandbox\/path_list.rb:128:in `relative_glob'",
    "\/Users\/cocoadocs\/.rvm\/gems\/ruby-2.1.3\/gems\/cocoapods-1.1.1\/lib\/cocoapods\/sandbox\/path_list.rb:90:in `glob'",
    "\/Users\/cocoadocs\/.rvm\/gems\/ruby-2.1.3\/gems\/cocoapods-1.1.1\/lib\/cocoapods\/sandbox\/file_accessor.rb:363:in `expanded_paths'",
    "\/Users\/cocoadocs\/.rvm\/gems\/ruby-2.1.3\/gems\/cocoapods-1.1.1\/lib\/cocoapods\/sandbox\/file_accessor.rb:334:in `paths_for_attribute'",
    "\/Users\/cocoadocs\/.rvm\/gems\/ruby-2.1.3\/gems\/cocoapods-1.1.1\/lib\/cocoapods\/sandbox\/file_accessor.rb:81:in `source_files'",
    "\/Users\/cocoadocs\/.rvm\/gems\/ruby-2.1.3\/gems\/cocoapods-1.1.1\/lib\/cocoapods\/sandbox\/file_accessor.rb:109:in `headers'",
    "\/Users\/cocoadocs\/.rvm\/gems\/ruby-2.1.3\/gems\/cocoapods-1.1.1\/lib\/cocoapods\/sandbox\/file_accessor.rb:122:in `public_headers'",
    "\/Users\/cocoadocs\/cocoadocs.org\/classes\/docset_generator.rb:134:in `block (2 levels) in headers_for_spec_at_location'",
    "\/Users\/cocoadocs\/cocoadocs.org\/classes\/docset_generator.rb:130:in `each'",
    "\/Users\/cocoadocs\/cocoadocs.org\/classes\/docset_generator.rb:130:in `block in headers_for_spec_at_location'",
    "\/Users\/cocoadocs\/cocoadocs.org\/classes\/docset_generator.rb:129:in `each'",
    "\/Users\/cocoadocs\/cocoadocs.org\/classes\/docset_generator.rb:129:in `headers_for_spec_at_location'",
    "\/Users\/cocoadocs\/cocoadocs.org\/classes\/docset_generator.rb:16:in `docset_command'",
    "\/Users\/cocoadocs\/cocoadocs.org\/classes\/docset_generator.rb:74:in `create_docset'",
    "\/Users\/cocoadocs\/cocoadocs.org\/.\/cocoadocs.rb:454:in `document_spec'",
    "\/Users\/cocoadocs\/cocoadocs.org\/.\/cocoadocs.rb:508:in `document_spec_at_path'",
    "\/Users\/cocoadocs\/cocoadocs.org\/.\/cocoadocs.rb:152:in `block in doc'",
    "\/Users\/cocoadocs\/cocoadocs.org\/.\/cocoadocs.rb:147:in `each'",
    "\/Users\/cocoadocs\/cocoadocs.org\/.\/cocoadocs.rb:147:in `doc'",
    "\/Users\/cocoadocs\/cocoadocs.org\/.\/cocoadocs.rb:219:in `block in cocoadocs_url'",
    "\/Users\/cocoadocs\/.rvm\/rubies\/ruby-2.1.3\/lib\/ruby\/2.1.0\/open-uri.rb:153:in `open_uri'",
    "\/Users\/cocoadocs\/.rvm\/rubies\/ruby-2.1.3\/lib\/ruby\/2.1.0\/open-uri.rb:704:in `open'",
    "\/Users\/cocoadocs\/.rvm\/rubies\/ruby-2.1.3\/lib\/ruby\/2.1.0\/open-uri.rb:34:in `open'",
    "\/Users\/cocoadocs\/cocoadocs.org\/.\/cocoadocs.rb:216:in `cocoadocs_url'",
    "\/Users\/cocoadocs\/cocoadocs.org\/.\/cocoadocs.rb:167:in `cocoadocs'",
    "\/Users\/cocoadocs\/cocoadocs.org\/.\/cocoadocs.rb:102:in `initialize'",
    "\/Users\/cocoadocs\/cocoadocs.org\/.\/cocoadocs.rb:540:in `new'",
    "\/Users\/cocoadocs\/cocoadocs.org\/.\/cocoadocs.rb:540:in `<main>'"
  ]
}
```

I am unsure of why it would be trying to read that folder as I don't see anything in my `Podspec` that would imply that the sources are in `UberRides`. If that's a convention we need to adopt, I can move it over, though.

**Comment by edjiang** [comment]
(If this is larger than a minor question, lmk and I can open up a new ticket)
