### ISSUE TITLE
Class documentation not generated

### ISSUE THREAD

**Issue by edjiang** [CocoaPods/cocoadocs.org#547]
The documentation for [UberRides](http://cocoadocs.org/docsets/UberRides/0.7.0/) doesn't seem to be generating anything beyond the README; I noticed that the errors endpoint now says:

```
{
  "message": "\u001b[31m[!] Attempt to read non existent folder `\/Users\/cocoadocs\/cocoadocs.org\/activity\/download\/UberRides\/0.7.0\/UberRides`.\u001b[0m",
  "trace": [
    "\/Users\/cocoadocs\/.rvm\/gems\/ruby-2.1.3\/gems\/cocoapods-1.1.1\/lib\/cocoapods\/sandbox\/path_list.rb:51:in `read_file_system'",
    "\/Users\/cocoadocs\/.rvm\/gems\/ruby-2.1.3\/gems\/cocoapods-1.1.1\/lib\/cocoapods\/sandbox\/path_list.rb:34:in `files'",
    "\/Users\/cocoadocs\/.rvm\/gems\/ruby-2.1.3\/gems\/cocoapods-1.1.1\/lib\/cocoapods\/sandbox\/path_list.rb:128:in `relative_glob'",
    "\/Users\/cocoadocs\/.rvm\/gems\/ruby-2.1.3\/gems\/cocoapods-1.1.1\/lib\/cocoapods\/sandbox\/path_list.rb:90:in `glob'",
    "\/Users\/cocoadocs\/.rvm\/gems\/ruby-2.1.3\/gems\/cocoapods-1.1.1\/lib\/cocoapods\/sandbox\/file_accessor.rb:363:in `expanded_paths'",
    "\/Users\/cocoadocs\/.rvm\/gems\/ruby-2.1.3\/gems\/cocoapods-1.1.1\/lib\/cocoapods\/sandbox\/file_accessor.rb:334:in `paths_for_attribute'",
    "\/Users\/cocoadocs\/.rvm\/gems\/ruby-2.1.3\/gems\/cocoapods-1.1.1\/lib\/cocoapods\/sandbox\/file_accessor.rb:81:in `source_files'",
    "\/Users\/cocoadocs\/.rvm\/gems\/ruby-2.1.3\/gems\/cocoapods-1.1.1\/lib\/cocoapods\/sandbox\/file_accessor.rb:109:in `headers'",
    "\/Users\/cocoadocs\/.rvm\/gems\/ruby-2.1.3\/gems\/cocoapods-1.1.1\/lib\/cocoapods\/sandbox\/file_accessor.rb:122:in `public_headers'",
    "\/Users\/cocoadocs\/cocoadocs.org\/classes\/docset_generator.rb:134:in `block (2 levels) in headers_for_spec_at_location'",
    "\/Users\/cocoadocs\/cocoadocs.org\/classes\/docset_generator.rb:130:in `each'",
    "\/Users\/cocoadocs\/cocoadocs.org\/classes\/docset_generator.rb:130:in `block in headers_for_spec_at_location'",
    "\/Users\/cocoadocs\/cocoadocs.org\/classes\/docset_generator.rb:129:in `each'",
    "\/Users\/cocoadocs\/cocoadocs.org\/classes\/docset_generator.rb:129:in `headers_for_spec_at_location'",
    "\/Users\/cocoadocs\/cocoadocs.org\/classes\/docset_generator.rb:16:in `docset_command'",
    "\/Users\/cocoadocs\/cocoadocs.org\/classes\/docset_generator.rb:74:in `create_docset'",
    "\/Users\/cocoadocs\/cocoadocs.org\/.\/cocoadocs.rb:454:in `document_spec'",
    "\/Users\/cocoadocs\/cocoadocs.org\/.\/cocoadocs.rb:508:in `document_spec_at_path'",
    "\/Users\/cocoadocs\/cocoadocs.org\/.\/cocoadocs.rb:152:in `block in doc'",
    "\/Users\/cocoadocs\/cocoadocs.org\/.\/cocoadocs.rb:147:in `each'",
    "\/Users\/cocoadocs\/cocoadocs.org\/.\/cocoadocs.rb:147:in `doc'",
    "\/Users\/cocoadocs\/cocoadocs.org\/.\/cocoadocs.rb:219:in `block in cocoadocs_url'",
    "\/Users\/cocoadocs\/.rvm\/rubies\/ruby-2.1.3\/lib\/ruby\/2.1.0\/open-uri.rb:153:in `open_uri'",
    "\/Users\/cocoadocs\/.rvm\/rubies\/ruby-2.1.3\/lib\/ruby\/2.1.0\/open-uri.rb:704:in `open'",
    "\/Users\/cocoadocs\/.rvm\/rubies\/ruby-2.1.3\/lib\/ruby\/2.1.0\/open-uri.rb:34:in `open'",
    "\/Users\/cocoadocs\/cocoadocs.org\/.\/cocoadocs.rb:216:in `cocoadocs_url'",
    "\/Users\/cocoadocs\/cocoadocs.org\/.\/cocoadocs.rb:167:in `cocoadocs'",
    "\/Users\/cocoadocs\/cocoadocs.org\/.\/cocoadocs.rb:102:in `initialize'",
    "\/Users\/cocoadocs\/cocoadocs.org\/.\/cocoadocs.rb:540:in `new'",
    "\/Users\/cocoadocs\/cocoadocs.org\/.\/cocoadocs.rb:540:in `<main>'"
  ]
}
```

I am unsure of why it would be trying to read that folder as I don't see anything in my `Podspec` that would imply that the sources are in `UberRides`.

**Comment by Palleas** [comment]
Hi there! We're moving cocoadocs.org to a new architecture tomorrow. If the issue persists we'll investigate further.

**Comment by edjiang** [comment]
Sounds great!

**Comment by SanjithKanagavel** [comment]
Hey. I have updated a new version to FreshchatSDK pod. But the latest docs has not generated. 
http://cocoadocs.org/docsets/FreshchatSDK/1.1.0/

**Comment by RudyB** [comment]
@Palleas any work about the transition?

**Comment by SanjithKanagavel** [comment]
@orta help here please ?

**Comment by Palleas** [comment]
Hi there - We have some issues with generating doc right now, definitely something dumb that we hope to resolve asap. Sorry about that!

**Comment by edjiang** [comment]
Not stale.

**Comment by SanjithKanagavel** [comment]
Still this one fails : http://cocoadocs.org/docsets/FreshchatSDK/1.2.2 @edjiang  please help.

**Comment by Palleas** [comment]
We're still working on it, I'll update this once we have news.

**Comment by edjiang** [comment]
Not stale.

**Comment by edjiang** [comment]
@Palleas, mind reopening?

**Comment by SanjithKanagavel** [comment]
Yes. Still it fails for the recent update. (http://cocoadocs.org/docsets/FreshchatSDK/1.3.0)
