### ISSUE TITLE
Swift 4 not supported for doc generation

### ISSUE THREAD

**Issue by johnhammerlund** [CocoaPods/cocoadocs.org#549]
I'm getting this error when attempting to generate source documentation for [Conduit](https://cocoapods.org/pods/Conduit):
```
{
  "message": "Unable to find an Xcode with swift version 4.0.",
  "trace": [
    "\/Users\/cocoadocs\/.rvm\/gems\/ruby-2.1.3\/bundler\/gems\/Jazzy-ca9e543123af\/lib\/jazzy\/sourcekitten.rb:210:in `run_sourcekitten'",
    "\/Users\/cocoadocs\/.rvm\/gems\/ruby-2.1.3\/bundler\/gems\/Jazzy-ca9e543123af\/lib\/jazzy\/podspec_documenter.rb:30:in `block (3 levels) in sourcekitten_output'",
    "\/Users\/cocoadocs\/.rvm\/gems\/ruby-2.1.3\/bundler\/gems\/Jazzy-ca9e543123af\/lib\/jazzy\/podspec_documenter.rb:26:in `map'",
    "\/Users\/cocoadocs\/.rvm\/gems\/ruby-2.1.3\/bundler\/gems\/Jazzy-ca9e543123af\/lib\/jazzy\/podspec_documenter.rb:26:in `block (2 levels) in sourcekitten_output'",
    "\/Users\/cocoadocs\/.rvm\/gems\/ruby-2.1.3\/bundler\/gems\/Jazzy-ca9e543123af\/lib\/jazzy\/podspec_documenter.rb:21:in `chdir'",
    "\/Users\/cocoadocs\/.rvm\/gems\/ruby-2.1.3\/bundler\/gems\/Jazzy-ca9e543123af\/lib\/jazzy\/podspec_documenter.rb:21:in `block in sourcekitten_output'",
    "\/Users\/cocoadocs\/.rvm\/gems\/ruby-2.1.3\/gems\/cocoapods-1.1.1\/lib\/cocoapods\/config.rb:41:in `with_changes'",
    "\/Users\/cocoadocs\/.rvm\/gems\/ruby-2.1.3\/bundler\/gems\/Jazzy-ca9e543123af\/lib\/jazzy\/podspec_documenter.rb:17:in `sourcekitten_output'",
    "\/Users\/cocoadocs\/.rvm\/gems\/ruby-2.1.3\/bundler\/gems\/Jazzy-ca9e543123af\/lib\/jazzy\/doc_builder.rb:63:in `build'",
    "\/Users\/cocoadocs\/cocoadocs.org\/.\/cocoadocs.rb:438:in `document_spec'",
    "\/Users\/cocoadocs\/cocoadocs.org\/.\/cocoadocs.rb:508:in `document_spec_at_path'",
    "\/Users\/cocoadocs\/cocoadocs.org\/.\/cocoadocs.rb:152:in `block in doc'",
    "\/Users\/cocoadocs\/cocoadocs.org\/.\/cocoadocs.rb:147:in `each'",
    "\/Users\/cocoadocs\/cocoadocs.org\/.\/cocoadocs.rb:147:in `doc'",
    "\/Users\/cocoadocs\/cocoadocs.org\/.\/cocoadocs.rb:219:in `block in cocoadocs_url'",
    "\/Users\/cocoadocs\/.rvm\/rubies\/ruby-2.1.3\/lib\/ruby\/2.1.0\/open-uri.rb:153:in `open_uri'",
    "\/Users\/cocoadocs\/.rvm\/rubies\/ruby-2.1.3\/lib\/ruby\/2.1.0\/open-uri.rb:704:in `open'",
    "\/Users\/cocoadocs\/.rvm\/rubies\/ruby-2.1.3\/lib\/ruby\/2.1.0\/open-uri.rb:34:in `open'",
    "\/Users\/cocoadocs\/cocoadocs.org\/.\/cocoadocs.rb:216:in `cocoadocs_url'",
    "\/Users\/cocoadocs\/cocoadocs.org\/.\/cocoadocs.rb:167:in `cocoadocs'",
    "\/Users\/cocoadocs\/cocoadocs.org\/.\/cocoadocs.rb:102:in `initialize'",
    "\/Users\/cocoadocs\/cocoadocs.org\/.\/cocoadocs.rb:540:in `new'",
    "\/Users\/cocoadocs\/cocoadocs.org\/.\/cocoadocs.rb:540:in `<main>'"
  ]
}
```

Either Xcode 9 hasn't been set up on cocoadocs.org, or Jazzy is otherwise failing to resolve the correct Swift toolchain.

**Comment by mayankk2308** [comment]
My README + Changelog has not been updated for v2.0.0 of my [pod](https://cocoapods.org/pods/MKDataDetector)...

**Comment by RudyB** [comment]
Jazzy works on my Mac when I do doc generation for my swift 4 Xcode project. However I don’t believe cocoapods has updated their version of jazzy to support swift 4

**Comment by orta** [comment]
Yeah, I stopped updating the server [back in May](http://blog.cocoapods.org/CocoaDocs-Documentation-Sunsetting/) but there's new infrastructure handled by @Palleas which should get Swift 4 support

**Comment by Palleas** [comment]
Yep! It’s coming!

**Comment by RudyB** [comment]
@Palleas Is there any public timeframe?

**Comment by Palleas** [comment]
Hopefully soon, trying to figure out why jazzy can't find the proper version of Xcode to use, cf #552

**Comment by Palleas** [comment]
Found the issue. Should be an easy fix on Monday. 👌

**Comment by dev4dev** [comment]
@Palleas hello, any updates on this?

**Comment by Palleas** [comment]
Still working on an infrastructure issue. I'll make sure to ping you once it's available.

**Comment by RudyB** [comment]
Not stale

**Comment by RudyB** [comment]
Not stale

**Comment by rvi** [comment]
any update @Palleas ?

**Comment by orta** [comment]
Yep, I have an update: https://github.com/CocoaPods/cocoadocs.org/issues/573#issuecomment-356319669

CocoaDocs is going to be fully shut down when I find the time, so it will never support Swift 4
